modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modUrl="${mod_url}"
displayURL="${mod_url}"

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile = "assets/${mod_id}/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

#[[dependencies.${mod_id}]]
#    modId="farmersdelight"
#    type="optional"
#    versionRange="${minecraft_version_range}"
#    ordering="NONE"
#    side="BOTH"

[modproperties.${mod_id}]
catalogueImageIcon = "assets/${mod_id}/icon.png"
catalogueBackground = "assets/${mod_id}/background.png"
